// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 

#include ".pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_ = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\000"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table__deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table__sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table__once;
static bool descriptor_table__initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ = {
  &descriptor_table__initialized, descriptor_table_protodef_, "", 2,
  &descriptor_table__once, descriptor_table__sccs, descriptor_table__deps, 0, 0,
  schemas, file_default_instances, TableStruct_::offsets,
  file_level_metadata_, 0, file_level_enum_descriptors_, file_level_service_descriptors_,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_), true);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
